name: Check Modified Files

on:
  workflow_call:
    outputs:
      modified_files:
        description: "List of modified files"
        value: ${{ jobs.check-modified-files.outputs.modified_files }}

jobs:
  check-modified-files:
    runs-on: ubuntu-latest
    outputs:
      modified_files: ${{ steps.get-diff.outputs.modified_files }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get the list of modified files
        id: get-diff
        run: |
          git fetch --depth=2
          echo "Before: ${{ github.event.before }}"
          echo "After: ${{ github.event.after }}"

          # Check if either 'before' or 'after' is empty
          if [ -z "${{ github.event.before }}" ] || [ -z "${{ github.event.after }}" ]; then
            echo "Either 'before' or 'after' commit is empty, skipping this job"
            exit 0
          fi

          echo "som tu"

          git diff --name-only ${{ github.event.before }} ${{ github.event.after }} > modified-files.txt
          cat modified-files.txt
          modified_files=$(tr '\n' ',' < modified-files.txt | sed 's/,$//')
          echo "modified_files=$modified_files" >> $GITHUB_OUTPUT
