name: Check Modified Files

on:
  workflow_call:
    outputs:
      modified_files:
        description: "List of modified files"
        value: ${{ jobs.check-modified-files.outputs.modified_files }}

jobs:
  check-modified-files:
    runs-on: ubuntu-latest
    outputs:
      modified_files: ${{ steps.get-diff.outputs.modified_files }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get the list of modified files
        id: get-diff
        run: |
          # Check if either 'before' or 'after' is empty
          if [ -z "${{ github.event.before }}" ] || [ -z "${{ github.event.after }}" ]; then
            echo "Skipping this job, manual trigger was used."
            exit 0
          else
            echo "Commit Before: ${{ github.event.before }}"
            echo "Commit After: ${{ github.event.after }}"
          fi

          git fetch --depth=2
          git diff --name-only ${{ github.event.before }} ${{ github.event.after }} > modified-files.txt
          
          echo "Modified files in last commit:"
          cat modified-files.txt

          echo "Make list of modified files available as output ..."
          modified_files=$(tr '\n' ',' < modified-files.txt | sed 's/,$//')
          echo "modified_files=$modified_files" >> $GITHUB_OUTPUT
