name: GS organization

on:
  push:
    paths:
      - "GS/**"   # Trigger if any change happens in GS folder
  workflow_dispatch:  # Allow manual triggering of the workflow
    inputs:
      region:
        description: 'Select the region to run'
        required: true
        default: 'eu-west-1 (plint)'
        type: choice
        options:
          - 'eu-west-1'
          - 'eu-west-1 (plint)'
          - 'eu-central-1'
          - 'us-west-2'

jobs:
  check-modified-files:
    uses: ./.github/workflows/check-modified-files.yaml

  get-artifact-eu-west-1:
    name: prod-euw1
    uses: ./.github/workflows/retrieve-artifact.yaml
    needs: [check-modified-files]
    if: ${{ contains(needs.check-modified-files.outputs.modified_files, 'GS/eu-west-1/') || (github.event_name == 'workflow_dispatch' && github.event.inputs.region == 'eu-west-1') }}
    with:
      region: eu-west-1

  get-artifact-eu-central-1:
    name: prod-euc1
    uses: ./.github/workflows/retrieve-artifact.yaml
    needs: [check-modified-files]
    if: ${{ contains(needs.check-modified-files.outputs.modified_files, 'GS/eu-central-1/') || (github.event_name == 'workflow_dispatch' && github.event.inputs.region == 'eu-central-1') }}
    with:
      region: eu-central-1

  get-artifact-us-west-2:
    name: prod-usw2
    uses: ./.github/workflows/retrieve-artifact.yaml
    needs: [check-modified-files]
    if: ${{ contains(needs.check-modified-files.outputs.modified_files, 'GS/us-west-2/') || (github.event_name == 'workflow_dispatch' && github.event.inputs.region == 'us-west-2') }}
    with:
      region: us-west-2
  
  get-artifact-eu-west-1-plint:
    name: plint-euw1
    uses: ./.github/workflows/retrieve-artifact.yaml
    needs: [check-modified-files]
    if: ${{ contains(needs.check-modified-files.outputs.modified_files, 'GS/plint/eu-west-1/') || (github.event_name == 'workflow_dispatch' && github.event.inputs.region == 'eu-west-1 (plint)') }}
    with:
      region: eu-west-1

  create-deployer-role-eu-west-1:
    name: prod-euw1
    uses: ./.github/workflows/create-deployer-role.yaml
    needs: [get-artifact-eu-west-1]
    with:
      region: eu-west-1

  create-deployer-role-eu-central-1:
    name: prod-euc1
    uses: ./.github/workflows/create-deployer-role.yaml
    needs: [get-artifact-eu-central-1]
    with:
      region: eu-central-1

  create-deployer-role-us-west-2:
    name: prod-usw2
    uses: ./.github/workflows/create-deployer-role.yaml
    needs: [get-artifact-us-west-2]
    with:
      region: us-west-2
  
  create-deployer-role-eu-west-1-plint:
    name: plint-euw1
    uses: ./.github/workflows/create-deployer-role.yaml
    needs: [get-artifact-eu-west-1-plint]
    with:
      region: eu-west-1

  deploy-cfn-stack-eu-west-1:
    name: prod-euw1
    needs: create-deployer-role-eu-west-1
    uses: ./.github/workflows/deploy-cfn-stack.yaml
    with:
      region: eu-west-1

  deploy-cfn-stack-eu-central-1:
    name: prod-euc1
    needs: create-deployer-role-eu-central-1
    uses: ./.github/workflows/deploy-cfn-stack.yaml
    with:
      region: eu-central-1

  deploy-cfn-stack-us-west-2:
    name: prod-usw2
    needs: create-deployer-role-us-west-2
    uses: ./.github/workflows/deploy-cfn-stack.yaml
    with:
      region: us-west-2
  
  deploy-cfn-stack-eu-west-1-plint:
    name: plint-euw1
    needs: create-deployer-role-eu-west-1-plint
    uses: ./.github/workflows/deploy-cfn-stack.yaml
    with:
      region: eu-west-1
  
  