name: GS organization

on:
  push:
    paths:
      - "GS/eu-west-1/**"   # Trigger if any change happens in GS/eu-west-1/
      - "GS/eu-central-1/**"  # Trigger if any change happens in GS/eu-central-1/
      - "GS/us-west-2/**"   # Trigger if any change happens in GS/us-west-2/
  workflow_dispatch:  # Allow manual triggering of the workflow
    inputs:
      region:
        description: 'Select the region to run'
        required: true
        default: 'eu-west-1'
        type: choice
        options:
          - 'eu-west-1'
          - 'eu-central-1'
          - 'us-west-2'

jobs:
  check-modified-files:
    runs-on: ubuntu-latest
    outputs:
      modified_files: ${{ steps.get-diff.outputs.modified_files }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get the list of modified files
        id: get-diff
        run: |
          # Ensure we fetch the latest commit and refs
          git fetch --depth=2
          echo "Fetching commit history"
          echo "Before: ${{ github.event.before }}"
          echo "After: ${{ github.event.after }}"

          # Get the modified files using the commit hashes from the event
          git diff --name-only ${{ github.event.before }} ${{ github.event.after }} > modified-files.txt
          
          # Output the list of modified files
          echo "Modified files:"
          cat modified-files.txt
          
          # Convert list of modified files to a single string, using comma as delimiter
          modified_files=$(cat modified-files.txt | tr '\n' ',')
          cat $modified_files
          
          # Set the modified files as output
          echo "modified_files=$(cat modified-files.txt)" >> $GITHUB_OUTPUT

  eu-west-1:
    runs-on: ubuntu-latest
    needs: check-modified-files
    if: ${{ contains(needs.check-modified-files.outputs.modified_files, 'GS/eu-west-1/') || (github.event_name == 'workflow_dispatch' && github.event.inputs.region == 'eu-west-1') }}
    steps:
      - name: Hello world from eu-west-1
        run: echo "Hello world from GS! (eu-west-1)"

  eu-central-1:
    runs-on: ubuntu-latest
    needs: check-modified-files
    if: ${{ contains(needs.check-modified-files.outputs.modified_files, 'GS/eu-central-1/') || (github.event_name == 'workflow_dispatch' && github.event.inputs.region == 'eu-central-1') }}
    steps:
      - name: Hello world from eu-central-1
        run: echo "Hello world from GS! (eu-central-1)"

  us-west-2:
    runs-on: ubuntu-latest
    needs: check-modified-files
    if: ${{ contains(needs.check-modified-files.outputs.modified_files, 'GS/us-west-2/') || (github.event_name == 'workflow_dispatch' && github.event.inputs.region == 'us-west-2') }}
    steps:
      - name: Hello world from us-west-2
        run: echo "Hello world from GS! (us-west-2)"
