name: GS organization

on:
  push:
    paths:
      - "GS/eu-west-1/**"   # Trigger if any change happens in GS/eu-west-1/
      - "GS/eu-central-1/**"  # Trigger if any change happens in GS/eu-central-1/
      - "GS/us-west-2/**"   # Trigger if any change happens in GS/us-west-2/
  workflow_dispatch:  # Allow manual triggering of the workflow
    inputs:
      region:
        description: 'Select the region to run'
        required: true
        default: 'eu-west-1'
        type: choice
        options:
          - 'eu-west-1'
          - 'eu-central-1'
          - 'us-west-2'

jobs:
  check-modified-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for modified files
        id: modified-files
        run: |
          # Get the list of modified files
          git fetch origin ${{ github.event.after }}
          git diff --name-only ${{ github.event.before }} ${{ github.event.after }} > modified-files.txt
          echo "Modified files:"
          cat modified-files.txt
          echo "modified_files=$(cat modified-files.txt)" >> $GITHUB_ENV

  eu-west-1:
    runs-on: ubuntu-latest
    needs: check-modified-files
    if: ${{ contains(needs.check-modified-files.outputs.modified_files, 'GS/eu-west-1/') || (github.event_name == 'workflow_dispatch' && github.event.inputs.region == 'eu-west-1') }}
    steps:
      - name: Hello world from eu-west-1
        run: echo "Hello world from GS! (eu-west-1)"

  eu-central-1:
    runs-on: ubuntu-latest
    needs: check-modified-files
    if: ${{ contains(needs.check-modified-files.outputs.modified_files, 'GS/eu-central-1/') || (github.event_name == 'workflow_dispatch' && github.event.inputs.region == 'eu-central-1') }}
    steps:
      - name: Hello world from eu-central-1
        run: echo "Hello world from GS! (eu-central-1)"

  us-west-2:
    runs-on: ubuntu-latest
    needs: check-modified-files
    if: ${{ contains(needs.check-modified-files.outputs.modified_files, 'GS/us-west-2/') || (github.event_name == 'workflow_dispatch' && github.event.inputs.region == 'us-west-2') }}
    steps:
      - name: Hello world from us-west-2
        run: echo "Hello world from GS! (us-west-2)"
