name: GS organization

on: workflow_dispatch

jobs:
  eu-west-1:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: echo "Hello world from GS!"
  eu-central-1:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: echo "Hello world from GS!"
    us-west-2:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: echo "Hello world from GS!"
