name: PP organization

on:
  push:
    paths:
      - "PP/**"   # Trigger if any change happens in PP folder
  workflow_dispatch:  # Allow manual triggering of the workflow
    inputs:
      region:
        description: 'Select the region to run'
        required: true
        default: 'eu-west-1'
        type: choice
        options:
          - 'eu-west-1'
          - 'eu-central-1'
          - 'us-west-2'

jobs:
  check-modified-files:
    uses: ./.github/workflows/check-modified-files.yaml

  deploy:
    runs-on: ubuntu-latest
    needs: [check-modified-files]
    strategy:
      matrix:
        region: ['eu-west-1', 'eu-central-1', 'us-west-2']
    steps:
      - name: Check if region is modified or workflow dispatched
        if: ${{ contains(needs.check-modified-files.outputs.modified_files, 'PP/${{ matrix.region }}/') || (github.event_name == 'workflow_dispatch' && github.event.inputs.region == matrix.region) }}
        run: echo "Proceeding with region ${{ matrix.region }}"

      - name: Get Artifact for ${{ matrix.region }}
        run: echo "Artifact successfully retrieved for region ${{ matrix.region }}"

      - name: Create Deployer Role for ${{ matrix.region }}
        run: echo "Deployer role successfully created for region ${{ matrix.region }}"

      - name: Deploy CFN Stack for ${{ matrix.region }}
        run: echo "CFN Stack successfully deployed for region ${{ matrix.region }}"
