name: PP organization

on:
  push:
    paths:
      - "PP/**"   # Trigger if any change happens in PP folder
  workflow_dispatch:  # Allow manual triggering of the workflow
    inputs:
      region:
        description: 'Select the region to run'
        required: true
        default: 'eu-west-1'
        type: choice
        options:
          - 'eu-west-1'
          - 'eu-central-1'
          - 'us-west-2'

jobs:
  check-modified-files:
    uses: ./.github/workflows/check-modified-files.yaml

  get-artifact-eu-west-1:
    name: eu-west-1
    uses: ./.github/workflows/retrieve-artifact.yaml
    needs: [check-modified-files]
    if: ${{ contains(needs.check-modified-files.outputs.modified_files, 'PP/eu-west-1/') || (github.event_name == 'workflow_dispatch' && github.event.inputs.region == 'eu-west-1') }}
    with:
      region: eu-west-1

  get-artifact-eu-central-1:
    name: eu-central-1
    uses: ./.github/workflows/retrieve-artifact.yaml
    needs: [check-modified-files]
    if: ${{ contains(needs.check-modified-files.outputs.modified_files, 'PP/eu-central-1/') || (github.event_name == 'workflow_dispatch' && github.event.inputs.region == 'eu-central-1') }}
    with:
      region: eu-central-1

  get-artifact-us-west-2:
    name: us-west-2
    uses: ./.github/workflows/retrieve-artifact.yaml
    needs: [check-modified-files]
    if: ${{ contains(needs.check-modified-files.outputs.modified_files, 'PP/us-west-2/') || (github.event_name == 'workflow_dispatch' && github.event.inputs.region == 'us-west-2') }}
    with:
      region: us-west-2

  create-deployer-role-eu-west-1:
    name: eu-west-1
    uses: ./.github/workflows/create-deployer-role.yaml
    needs: [get-artifact-eu-west-1]
    with:
      region: eu-west-1

  create-deployer-role-eu-central-1:
    name: eu-central-1
    uses: ./.github/workflows/create-deployer-role.yaml
    needs: [get-artifact-eu-central-1]
    with:
      region: eu-central-1

  create-deployer-role-us-west-2:
    name: us-west-2
    uses: ./.github/workflows/create-deployer-role.yaml
    needs: [get-artifact-us-west-2]
    with:
      region: us-west-2

  deploy-cfn-stack-eu-west-1:
    name: eu-west-1
    uses: ./.github/workflows/deploy-cfn-stack.yaml
    with:
      region: eu-west-1

  deploy-cfn-stack-eu-central-1:
    name: eu-central-1
    uses: ./.github/workflows/deploy-cfn-stack.yaml
    with:
      region: eu-central-1

  deploy-cfn-stack-us-west-2:
    name: us-west-2
    uses: ./.github/workflows/deploy-cfn-stack.yaml
    with:
      region: us-west-2