name: PP organization

on:
  push:
    paths:
      - "PP/**"   # Trigger if any change happens in PP folder
  workflow_dispatch:  # Allow manual triggering of the workflow
    inputs:
      region:
        description: 'Select the region to run'
        required: true
        default: 'eu-west-1'
        type: choice
        options:
          - 'eu-west-1'
          - 'eu-central-1'
          - 'us-west-2'

jobs:
  check-modified-files:
    uses: ./.github/workflows/check-modified-files.yaml

  get-artifact-eu-west-1:
    runs-on: ubuntu-latest
    needs: [check-modified-files]
    if: ${{ contains(needs.check-modified-files.outputs.modified_files, 'PP/eu-west-1/') || (github.event_name == 'workflow_dispatch' && github.event.inputs.region == 'eu-west-1') }}
    steps:
      - name: Get S3 Artifact
        run: echo "Artifact Successfully retrieved ..."

  get-artifact-eu-central-1:
    runs-on: ubuntu-latest
    needs: [check-modified-files]
    if: ${{ contains(needs.check-modified-files.outputs.modified_files, 'PP/eu-central-1/') || (github.event_name == 'workflow_dispatch' && github.event.inputs.region == 'eu-central-1') }}
    steps:
      - name: Hello world from eu-central-1
        run: echo "Hello world from PP! (eu-central-1)"

  get-artifact-us-west-2:
    runs-on: ubuntu-latest
    needs: [check-modified-files]
    if: ${{ contains(needs.check-modified-files.outputs.modified_files, 'PP/us-west-2/') || (github.event_name == 'workflow_dispatch' && github.event.inputs.region == 'us-west-2') }}
    steps:
      - name: Hello world from us-west-2
        run: echo "Hello world from PP! (us-west-2)"

  create-deployer-role-eu-west-1:
    runs-on: ubuntu-latest
    needs: [get-artifact-eu-west-1]
    steps:
      - name: create the role
        run: |
          echo "Deployer role successfully created ..."

  create-deployer-role-eu-central-1:
    runs-on: ubuntu-latest
    needs: [get-artifact-eu-central-1]
    steps:
      - name: create the role
        run: |
          echo "Deployer role successfully created ..."
    create-deployer-role-us-west-2:
      runs-on: ubuntu-latest
      needs: [get-artifact-us-west-2]
      steps:
        - name: create the role
          run: |
            echo "Deployer role successfully created ..."
