name: PP organization

on: workflow_dispatch

jobs:
  eu-west-1:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: echo "Hello world from PP!"
  eu-central-1:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: echo "Hello world from PP!"
  us-west-2:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: echo "Hello world from PP!"
