name: Retrieve Artifact

on:
  workflow_call:
    inputs:
      region:
        required: true
        type: string

jobs:
  get-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve Artifact for ${{ inputs.region }}
        run: echo "Artifact successfully retrieved for ${{ inputs.region }}"